[[language]]
name = "python"
formatter = { command = "ruff format" , args = ["--quiet", "-"] }
language-servers = [ "pylsp" ]

[language-server.pylsp]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }


